#Numpy Introduction

In [2]:
pip install numpy

In [3]:
import numpy as np
print(np.__version__)

1.19.5


In [16]:
#1D Array

import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

print(type(arr))
print('bentuk array : ', arr.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
bentuk array :  (5,)


In [8]:
#2D Array

import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [14]:
import numpy as np
arr = np.array([[1, 2, 3, 6], [4, 5, 6, 8], [5, 6, 7, 9]])
print(arr)

print('bentuk array : ', arr.shape)

[[1 2 3 6]
 [4 5 6 8]
 [5 6 7 9]]
bentuk array :  (3, 4)


In [17]:
#3D Array

arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9],[10,11,12]]])
print(arr)

print('bentuk array : ', arr.shape)
print('dimensinya adalah : ', arr.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
bentuk array :  (2, 2, 3)
dimensinya adalah :  3


In [20]:
#Array indexing

arr = np.array([4,5,6,7])
print(arr[1])

print('')

print(arr[:3])
print(arr[1:])

5

[4 5 6]
[5 6 7]


In [22]:
arr = np.array([[1, 2, 3, 6], [4, 5, 6, 8], [5, 6, 7, 9]])
print(arr[1, 1])
print(arr[2, 3])

5
9


In [24]:
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9],[10,11,12]]])
print(arr[0, 1, 1])
print(arr[1, 0, 2])

5
9


In [28]:
#Array Slicing



arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[1:5])
print(arr[:5])
print(arr[3:])

print(arr[1:9:2])

[2 3 4 5]
[1 2 3 4 5]
[ 4  5  6  7  8  9 10]
[2 4 6 8]


In [31]:
arr = np.array([[1, 2, 3, 6], [4, 5, 6, 8], [5, 6, 7, 9]])
print(arr[0, 1:])
print(arr[1, :2])
print(arr[2, 2:])

[2 3 6]
[4 5]
[7 9]


In [32]:
#Convert Data Type

arr = np.array(['1', '2', '3', '4', '5'])
newarr = arr.astype(float)
print('sebelum : ', arr)
print('sesudah : ', newarr)

sebelum :  ['1' '2' '3' '4' '5']
sesudah :  [1. 2. 3. 4. 5.]


In [33]:
arr = np.array(['1', '2', '3', '4', '5'])
newarr = arr.astype('i')
print('sebelum : ', arr)
print('sesudah : ', newarr)

sebelum :  ['1' '2' '3' '4' '5']
sesudah :  [1 2 3 4 5]


In [36]:
#Array Reshape
#1D to 2D

arr = np.array([1,2,3,4,5,6,7,8,9,10])
newarr = arr.reshape(5,2)

print('sebelum ', arr)
print('sesudah \n', newarr)

sebelum  [ 1  2  3  4  5  6  7  8  9 10]
sesudah 
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [37]:
#1D to 3D

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2,2,3)
print('before : ', arr)
print('after : \n', newarr)

before :  [ 1  2  3  4  5  6  7  8  9 10 11 12]
after : 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [80]:
#2D to 1D

arr = np.array([[1, 2, 3, 6], [4, 5, 6, 8], [5, 6, 7, 9]])
newarr = arr.reshape(-1)

print(newarr)



[1 2 3 6 4 5 6 8 5 6 7 9]


In [39]:
#Array Iterating

arr = np.array([ 1,  2,  3,  4,  5,  6, 7,  8,  9, 10, 11, 12])
for i in arr:
  print(i, end=' ')


1 2 3 4 5 6 7 8 9 10 11 12 

In [40]:
arr = np.array([[1, 2, 3, 6], [4, 5, 6, 8], [5, 6, 7, 9]])
for i in arr:
  for j in i:
    print(j, end=' ')
  print(' ')

1 2 3 6  
4 5 6 8  
5 6 7 9  


In [42]:
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9],[10,11,12]]])
for i in arr:
  for j in i:
    for k in j:
      print(k, end=' ')
    print(' ')
  print(' ')

1 2 3  
4 5 6  
 
7 8 9  
10 11 12  
 


In [45]:
#Array Join

arr1 = np.array([1,2,3,4])
arr2 = np.array([7,8,9,10])

newarr = np.concatenate((arr1,arr2))

print(newarr)

[ 1  2  3  4  7  8  9 10]


In [49]:
arr1 = np.array([[1,2,3,4]])
arr2 = np.array([[7,8,9,10]])

newarr = np.concatenate((arr1,arr2), axis=0)

print(newarr)

[[ 1  2  3  4]
 [ 7  8  9 10]]


In [51]:
#Array Split

arr = np.array([ 1,  2,  3,  4,  5,  6, 7,  8,  9, 10, 11, 12])
newarr = np.array_split(arr, 3)

print('before : ', arr)
print('after : \n', newarr)
print(newarr[0])

before :  [ 1  2  3  4  5  6  7  8  9 10 11 12]
after : 
 [array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]
[1 2 3 4]


In [53]:
#Array Search
#Where

arr = np.array([ 1,  2,  3,  4,  5,  6, 7,  8,  9, 5, 11, 12])
newarr = np.where(arr == 5)
print(newarr)

(array([4, 9]),)


In [55]:
arr = np.array([[ 1,  2,  3,  4,  5, 6],[7,  8,  9, 5, 11, 12]])
newarr = np.where(arr == 5)
print(newarr)

(array([0, 1]), array([4, 3]))


In [56]:
#Array Sort

arr= np.array([6,7,8,9,5,11,1,2,3,4,5,12])
print(np.sort(arr))

[ 1  2  3  4  5  5  6  7  8  9 11 12]


In [78]:
arr = np.array(['maya', 'agus', 'joko', 4, 5, 1])
print(np.sort(arr))

['1' '4' '5' 'agus' 'joko' 'maya']


In [62]:
# Array Random

from numpy import random

x = random.rand()
print(x)

0.9850482903335845


In [66]:
x = random.randint(0, 12)
print(x)

2


In [67]:
x = random.randint(0, 12, size=(2,3))
print(x)

[[ 8  6  7]
 [ 3  6 10]]


In [69]:
#randon hanya dengan angka yang ada

arr= np.array([6,7,8,9,5,11,1,2,3,4,5,12])
x = random.choice(arr)
print(x)

5


In [72]:
#Ufuncs

arr1= np.array([6,7,8,9,5,11])
arr2= np.array([1,2,3,4,5,12])

arr3 = np.add(arr1,arr2)

print(arr3)

[ 7  9 11 13 10 23]


In [74]:
arr1= np.array([6,7,8,9,5,11])
arr2= np.array([1,2,3,4,5,12])

arr3 = np.subtract(arr1,arr2)

print(arr3)

[ 5  5  5  5  0 -1]


In [73]:
arr1= np.array([6,7,8,9,5,11])
arr2= np.array([1,2,3,4,5,12])

arr3 = np.multiply(arr1,arr2)

print(arr3)

[  6  14  24  36  25 132]


In [79]:
arr2 = np.array([1,2,3,4])
newarr = np.sum(arr2)
print(newarr)

10


In [83]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([2,4,5,6])

newarr = np.sum([arr1, arr2])
print(newarr)

27


In [82]:
arr2 = np.array([1,2,3,4])
newarr = np.prod(arr2)
print(newarr)

24
